// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NewsExtractor.Models;

public partial class RefreshingUnitContext : DbContext
{
    public RefreshingUnitContext(DbContextOptions<RefreshingUnitContext> options)
        : base(options)
    {
    }

    public virtual DbSet<InfoTable> InfoTables { get; set; }

    public virtual DbSet<RefreshingLink> RefreshingLinks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InfoTable>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__InfoTabl__3214EC076A95FE6B");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<RefreshingLink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Refreshi__3214EC07EA6D3C06");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}