// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsExtractor.Models;

[Table("RefreshingLink")]
public partial class RefreshingLink
{
    [Key]
    public int Id { get; set; }

    public string Link { get; set; }
}